version: '3.8'
services:
  mongodb-product-service:
    image: mongo:7.0.4
    container_name: microservices-mongodb-product-service
    volumes:
      - data-product-service:/data/db
    ports:
      - "27021:27017"

  postgres-order-service:
    image: "postgres:13.1"
    container_name: microservices-postgres-order-service
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data-order-service:/data/postgres

  postgres-inventory-service:
    image: "postgres:13.1"
    container_name: microservices-postgres-inventory-service
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data-inventory-service:/data/postgres

volumes:
  data-product-service:
  data-order-service:
  data-inventory-service: