spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers_skip_column_definitions: 'true'
        globally_quoted_identifiers: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/order-service
    password: postgres
  application:
    name: order-service

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/