spring:
  data:
    mongodb:
      uri: mongodb://localhost:27021/product-service
  application:
    name: product-service

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/